### ISSUE TITLE
An error occurred trying to process items for field "Campaign" (No site found in root line of page -17).

### ISSUE THREAD

**Issue by Weissheiten** [SkillDisplay/TYPO3ContentElements#11]
Reproduction:

- Inserting a content element (Skills or SkillSets) works as intended on the first try once templates, etc. are setup
- when inserting the second element the following error appears: "An error occurred trying to process items for field "Campaign" (No site found in root line of page -17)."
- The number (-17) changes depending on the number of content elements that have been inserted on the page (e.g.: if I add another "text" element and then retry to insert an element of type "skill" the number will change to -18

**Comment by liayn** [comment]
Is the second element inserted *above* the first one?

**Comment by Weissheiten** [comment]
no this also happens when the element is the only one on the page (skills or not).
The negative ID is always the one that the highest ID of the current CE on the page is

**Comment by liayn** [comment]
Then my fix is nuts
