### ISSUE TITLE
It's not possible to create contente elements

### ISSUE THREAD

**Issue by DanielSiepmann** [SkillDisplay/TYPO3ContentElements#5]
When inserting a new content element the following error is raised:
```
(1/1) ArgumentCountError

Too few arguments to function SkillDisplay\PHPToolKit\Api\Campaigns::__construct(), 0 passed in typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3431 and exactly 2 expected
```

The root cause seems to be the following part of the stack trace:
```
at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance()
in typo3conf/ext/skilldisplay/Classes/TcaEnhancer.php line 19

        $params['items'] = [
            ['', 0],
        ];

        $campaigns = GeneralUtility::makeInstance(Campaigns::class)->getForUser();
        /** @var Campaign $campaign */
        foreach ($campaigns as $campaign) {
            $params['items'][] = [
                $campaign->getTitle(),
```

**Comment by liayn** [comment]
Shouldn't the DI take care of this? The settings and the Client should be injected into the Campaigns
I do not have a local test-setup for this extension at the moment, so a can't debug.
Can you?

**Comment by DanielSiepmann** [comment]
I don't have time to investigate.

From first look, the code just can't work, as the `Campaigns` instance is not injected by DI, and is not marked to be public.
Migration to inject the instance might solve the issue.

**Comment by DanielSiepmann** [comment]
I will try to investigate this Friday, but can't make any promises.

**Comment by DanielSiepmann** [comment]
During investigation, the exception changed to:

```

(1/1) Error

Call to undefined method TYPO3\CMS\Core\Site\Entity\NullSite::getConfiguration()

/typo3conf/ext/skilldisplay/Classes/SettingsFactory.php line 36

        if ($site === null) {
            throw new \Exception('Could not determine current site.', 1599721652);
        }

        $config = $site->getConfiguration();

        return new Settings(
            $config['skilldisplay_api_key'] ?? '',
            (int)($config['skilldisplay_verifier_id'] ?? 0),

```

not sure about the change, but that exception makes way more sense and was the initial exception I remember back when first trying to add a new element with the recent changes.
