### ISSUE TITLE
default name for the extension ("skilldisplay") possible conflicts

### ISSUE THREAD

**Issue by Weissheiten** [SkillDisplay/TYPO3ContentElements#8]
Should be named skilldisplay-typo3
When installing the extension on a test system that has the "real" skilldisplay extension it doesn't appear in the extension list.
In the test case the site setup had the key "skilldisplay"

**Comment by liayn** [comment]
"naming things" ;-)

Not sure about "skilldisplay-typo3" either.
What about: "skilldisplay-content" ?

**Comment by Weissheiten** [comment]
I don't have any strong opinions on naming, but I guess it should match the composer name?  "name": "skilldisplay/typo3-skilldisplay",

**Comment by liayn** [comment]
That's not necessary. The extension key is defined in the composer.json. (Which is missing currently, so I'll push a fix for this.)

**Comment by liayn** [comment]
It's not missing, I was just blind: https://github.com/SkillDisplay/TYPO3ContentElements/blob/main/composer.json#L58
