### ISSUE TITLE
2: SQL error: 'Unknown column 'skilldisplay_campaign' in 'field list'' (tt_content:NEW600ecb1343f45692528578)

### ISSUE THREAD

**Issue by Weissheiten** [SkillDisplay/TYPO3ContentElements#9]
This happens on the branch that Daniel provided as fix.
The Database Tool tells me the Schema is up to date, when creating a skill entry however I get:
	
2: SQL error: 'Unknown column 'skilldisplay_campaign' in 'field list'' (tt_content:NEW600ecb1343f45692528578)

**Comment by liayn** [comment]
Strange, it is indeed missing in `ext_tables.sql`.
